// 主要国家和城市列表；value 为英文标识（存入后端），zh 为中文展示，en 为英文展示
export const LOCATIONS = [
    // ─── 中国 ──────────────────────────────────────────────
    {value: 'Beijing, China', zh: '北京，中国', en: 'Beijing, China'},
    {value: 'Shanghai, China', zh: '上海，中国', en: 'Shanghai, China'},
    {value: 'Shenzhen, China', zh: '深圳，中国', en: 'Shenzhen, China'},
    {value: 'Guangzhou, China', zh: '广州，中国', en: 'Guangzhou, China'},
    {value: 'Hangzhou, China', zh: '杭州，中国', en: 'Hangzhou, China'},
    {value: 'Chengdu, China', zh: '成都，中国', en: 'Chengdu, China'},
    {value: 'Wuhan, China', zh: '武汉，中国', en: 'Wuhan, China'},
    {value: 'Nanjing, China', zh: '南京，中国', en: 'Nanjing, China'},
    {value: 'Xi\'an, China', zh: '西安，中国', en: 'Xi\'an, China'},
    {value: 'Chongqing, China', zh: '重庆，中国', en: 'Chongqing, China'},
    {value: 'Tianjin, China', zh: '天津，中国', en: 'Tianjin, China'},
    {value: 'Suzhou, China', zh: '苏州，中国', en: 'Suzhou, China'},
    {value: 'Changsha, China', zh: '长沙，中国', en: 'Changsha, China'},
    {value: 'Qingdao, China', zh: '青岛，中国', en: 'Qingdao, China'},
    {value: 'Xiamen, China', zh: '厦门，中国', en: 'Xiamen, China'},
    {value: 'Hong Kong, China', zh: '香港，中国', en: 'Hong Kong, China'},
    {value: 'Taipei, Taiwan, China', zh: '台北，台湾，中国', en: 'Taipei, Taiwan, China'},
    {value: 'Macau, China', zh: '澳门，中国', en: 'Macau, China'},
    // ─── 日本 ──────────────────────────────────────────────
    {value: 'Tokyo, Japan', zh: '东京，日本', en: 'Tokyo, Japan'},
    {value: 'Osaka, Japan', zh: '大阪，日本', en: 'Osaka, Japan'},
    {value: 'Kyoto, Japan', zh: '京都，日本', en: 'Kyoto, Japan'},
    // ─── 韩国 ──────────────────────────────────────────────
    {value: 'Seoul, South Korea', zh: '首尔，韩国', en: 'Seoul, South Korea'},
    {value: 'Busan, South Korea', zh: '釜山，韩国', en: 'Busan, South Korea'},
    // ─── 东南亚 ──────────────────────────────────────────────
    {value: 'Singapore', zh: '新加坡', en: 'Singapore'},
    {value: 'Bangkok, Thailand', zh: '曼谷，泰国', en: 'Bangkok, Thailand'},
    {value: 'Kuala Lumpur, Malaysia', zh: '吉隆坡，马来西亚', en: 'Kuala Lumpur, Malaysia'},
    {value: 'Jakarta, Indonesia', zh: '雅加达，印度尼西亚', en: 'Jakarta, Indonesia'},
    {value: 'Manila, Philippines', zh: '马尼拉，菲律宾', en: 'Manila, Philippines'},
    {value: 'Ho Chi Minh City, Vietnam', zh: '胡志明市，越南', en: 'Ho Chi Minh City, Vietnam'},
    // ─── 南亚 / 中东 ──────────────────────────────────────
    {value: 'Mumbai, India', zh: '孟买，印度', en: 'Mumbai, India'},
    {value: 'Bangalore, India', zh: '班加罗尔，印度', en: 'Bangalore, India'},
    {value: 'New Delhi, India', zh: '新德里，印度', en: 'New Delhi, India'},
    {value: 'Dubai, UAE', zh: '迪拜，阿联酋', en: 'Dubai, UAE'},
    {value: 'Abu Dhabi, UAE', zh: '阿布扎比，阿联酋', en: 'Abu Dhabi, UAE'},
    {value: 'Tel Aviv, Israel', zh: '特拉维夫，以色列', en: 'Tel Aviv, Israel'},
    // ─── 大洋洲 ────────────────────────────────────────────
    {value: 'Sydney, Australia', zh: '悉尼，澳大利亚', en: 'Sydney, Australia'},
    {value: 'Melbourne, Australia', zh: '墨尔本，澳大利亚', en: 'Melbourne, Australia'},
    {value: 'Auckland, New Zealand', zh: '奥克兰，新西兰', en: 'Auckland, New Zealand'},
    // ─── 北美 ──────────────────────────────────────────────
    {value: 'New York, USA', zh: '纽约，美国', en: 'New York, USA'},
    {value: 'San Francisco, USA', zh: '旧金山，美国', en: 'San Francisco, USA'},
    {value: 'Los Angeles, USA', zh: '洛杉矶，美国', en: 'Los Angeles, USA'},
    {value: 'Seattle, USA', zh: '西雅图，美国', en: 'Seattle, USA'},
    {value: 'Chicago, USA', zh: '芝加哥，美国', en: 'Chicago, USA'},
    {value: 'Austin, USA', zh: '奥斯汀，美国', en: 'Austin, USA'},
    {value: 'Boston, USA', zh: '波士顿，美国', en: 'Boston, USA'},
    {value: 'Toronto, Canada', zh: '多伦多，加拿大', en: 'Toronto, Canada'},
    {value: 'Vancouver, Canada', zh: '温哥华，加拿大', en: 'Vancouver, Canada'},
    {value: 'Montreal, Canada', zh: '蒙特利尔，加拿大', en: 'Montreal, Canada'},
    // ─── 欧洲 ──────────────────────────────────────────────
    {value: 'London, UK', zh: '伦敦，英国', en: 'London, UK'},
    {value: 'Manchester, UK', zh: '曼彻斯特，英国', en: 'Manchester, UK'},
    {value: 'Paris, France', zh: '巴黎，法国', en: 'Paris, France'},
    {value: 'Berlin, Germany', zh: '柏林，德国', en: 'Berlin, Germany'},
    {value: 'Munich, Germany', zh: '慕尼黑，德国', en: 'Munich, Germany'},
    {value: 'Amsterdam, Netherlands', zh: '阿姆斯特丹，荷兰', en: 'Amsterdam, Netherlands'},
    {value: 'Stockholm, Sweden', zh: '斯德哥尔摩，瑞典', en: 'Stockholm, Sweden'},
    {value: 'Zurich, Switzerland', zh: '苏黎世，瑞士', en: 'Zurich, Switzerland'},
    {value: 'Dublin, Ireland', zh: '都柏林，爱尔兰', en: 'Dublin, Ireland'},
    {value: 'Madrid, Spain', zh: '马德里，西班牙', en: 'Madrid, Spain'},
    {value: 'Barcelona, Spain', zh: '巴塞罗那，西班牙', en: 'Barcelona, Spain'},
    {value: 'Milan, Italy', zh: '米兰，意大利', en: 'Milan, Italy'},
    {value: 'Moscow, Russia', zh: '莫斯科，俄罗斯', en: 'Moscow, Russia'},
    // ─── 南美 ──────────────────────────────────────────────
    {value: 'São Paulo, Brazil', zh: '圣保罗，巴西', en: 'São Paulo, Brazil'},
    // ─── 非洲 ──────────────────────────────────────────────
    {value: 'Cape Town, South Africa', zh: '开普敦，南非', en: 'Cape Town, South Africa'},
    {value: 'Nairobi, Kenya', zh: '内罗毕，肯尼亚', en: 'Nairobi, Kenya'},
    // ─── 其他 ──────────────────────────────────────────────
    {value: 'Remote', zh: '远程办公', en: 'Remote'},
]